name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/uni-social-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/uni-social-frontend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/uni-social-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/uni-social-frontend:buildcache,mode=max

      # Ejemplo de despliegue a un servidor mediante SSH
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/uni-social-frontend:latest
            docker stop uni-social-frontend || true
            docker rm uni-social-frontend || true
            docker run -d \
              --name uni-social-frontend \
              -p 3000:3000 \
              -e NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
              -e NEXT_PUBLIC_AUTH_SERVICE_URL=${{ secrets.NEXT_PUBLIC_AUTH_SERVICE_URL }} \
              -e NEXT_PUBLIC_CONTENT_SERVICE_URL=${{ secrets.NEXT_PUBLIC_CONTENT_SERVICE_URL }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/uni-social-frontend:latest